inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
  - 'db/schema.rb'
  - 'vendor//'
  - 'config/environments/.rb'
  - 'bin/*'

Rails:
  Enabled: True

Metrics/BlockLength:
  Exclude:
  - 'spec//*.rb'
  - 'Guardfile'
  - 'vendor/bundle'

inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
  - 'db/schema.rb'
  - 'vendor//'
  - 'config/environments/.rb'
  - 'bin/*'
  - 'spec/spec_helper.rb'
  NewCops: enable
  TargetRubyVersion: 3.0
  StyleGuideBaseURL: https://rails.rubystyle.guide/

Rails:
  Enabled: True

Metrics/BlockLength:
  Exclude:
  - 'spec//*.rb'
  - 'Guardfile'
  - 'vendor/bundle'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
require:
  - rubocop-rails
